### ISSUE TITLE
Pkg.add("HttpParser") gives ERROR: unknown package HttpParser

### ISSUE THREAD

**Issue by cgoldammer** [JuliaWeb/HttpParser.jl#30]
There's a good chance I'm just doing something wrong here and this error has nothing to do with HttpParser. However, other packages install fine, so I just wanted to flag it. I also had no luck when cloning the repository through ``Pkg.clone("https://github.com/JuliaWeb/HttpParser.jl")``.

```julia

julia> Pkg.add("HttpParser")
ERROR: unknown package HttpParser
 in wait at task.jl:51
 in sync_end at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib

julia> versioninfo()
Julia Version 0.3.6
Commit 0c24dca* (2015-02-17 22:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

```

**Comment by IainNZ** [comment]
That is really weird! What happens with the `Pkg.clone` version?

**Comment by cgoldammer** [comment]
Using a clean REPL, I get

```julia

julia> Pkg.clone("https://github.com/JuliaWeb/HttpParser.jl")
INFO: Cloning HttpParser from https://github.com/JuliaWeb/HttpParser.jl
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using HttpParser
ERROR: could not open file /Users/cg/.julia/v0.3/HttpParser/src/../deps/deps.jl
 in include at /Applications/Julia-0.3.6.app/Contents/Resources/julia/lib/julia/sys.dylib

```

**Comment by IainNZ** [comment]
Can you run `Pkg.build("HttpParser")`?

**Comment by cgoldammer** [comment]
That worked! Is the overall behavior still unexpected?

**Comment by IainNZ** [comment]
Oh yeah, definitely odd. I got no idea what thats about, would be interesting to see if it happens again. You'd need to nuke `~/.julia` to test that though...

**Comment by cgoldammer** [comment]
It looks like so far, it's just me. How about we wait if someone else has this problem? If so, I'm happy to test further.

**Comment by tkelman** [comment]
That include should really be guarded a la https://github.com/JuliaLang/ZMQ.jl/blob/732c7940f6c175b59ce8299c4a9975f7caa17e3c/src/ZMQ.jl#L6-L10 for a better error

May be some corrupt cloning of metadata or something? Did `Pkg.init(); Pkg.update()` go through properly?

**Comment by cgoldammer** [comment]
@tkelman: Thanks for the Yes, running ``Pkg.init(); Pkg.update()`` ran without problems. But I still can't find HttpParser.

**Comment by tkelman** [comment]
Does `ls -al ~/.julia/v0.4/METADATA` show any sign of HttpParser? Was this package ever renamed from some different casing?

**Comment by tkelman** [comment]
sorry, that should be `v0.3`, missed which version you were on

**Comment by iceblue25** [comment]
I have exactly the same issue here. Any ideas on how to fix it?
