### ISSUE TITLE
Reauthorize coveralls

### ISSUE THREAD

**Issue by hayd** [JuliaWeb/HttpParser.jl#34]
Currently looking at the [build of a file](https://coveralls.io/files/905761678):
```
SOURCE NOT AVAILABLE
The owner of this repo needs to re-authorize with Github; their OAuth credentials are no longer valid so the file cannot be pulled from the Github API.
```

**Comment by IainNZ** [comment]
Just regenerated the token on the website, not sure what happened with that build but it seems to be working fine now.

**Comment by hayd** [comment]
The build works fine it's looking at the source code where the issue is (hopefully it'll work the next time there's a push to master).

**Comment by IainNZ** [comment]
Ahh I see. Now I'm in some re-auth loop where it wants access to my private repositories or something. lol so broken.

**Comment by hayd** [comment]
Don't *quite* understand why it needs additional access to a view the source of a visible (open source) project. It appears to be working now: https://coveralls.io/files/905805983
