### ISSUE TITLE
Show Parser could be a more informative

### ISSUE THREAD

**Issue by hayd** [JuliaWeb/HttpParser.jl#35]
Currently it simply prints HttpParser, which doesn't seem very useful:
```
function show(io::IO,p::Parser)
    print(io,"HttpParser")
end
```
https://github.com/JuliaWeb/HttpParser.jl/blob/73395951134d3c9f3499367427de590d901d1636/src/HttpParser.jl#L81

**Comment by wildart** [comment]
What do you suggest to show?
