### ISSUE TITLE
Missing expression after unary operator '--'

### ISSUE THREAD

**Issue by EricForgy** [JuliaWeb/HttpParser.jl#38]
julia> versioninfo()
    Julia Version 0.4.0-rc1
    Commit e5c6964 (2015-09-09 16:07 UTC)
    Platform Info:
      System: Windows (x86_64-w64-mingw32)
      CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      WORD_SIZE: 64
      BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

Hi,

I am starting up some work again and was using Morsel.jl before, but see it is now deprecated with a suggestion to use Mux.jl instead. I just tried to add Mux.jl and got the following message when it got to building HttpParser:

    INFO: Building HttpParser
    At line:1 char:3
    + --help
    +   ~ 
    Missing expression after unary operator '--'.
    At line:1 char:3
    + --help
    +   ~~~~
    Unexpected token 'help' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingExpressionAfterOperator

Just FYI.

**Comment by IainNZ** [comment]
Thats really strange. Can you confirm you are using latest version of all packages? Does this happen if you `Pkg.build` again?

**Comment by EricForgy** [comment]
Pkg.build() seemed to do the trick. I'm still a newbie and learning the ropes. Thanks!
