### ISSUE TITLE
Pkg.test fails:  ccall: could not find function http_parser_version in library libhttp_parser64.dll

### ISSUE THREAD

**Issue by musm** [JuliaWeb/HttpParser.jl#59]
I can't seem to figure out why this happens.

I cross compiled 32 and 64 bit version as per instructions in the readme. Short story for some reason the 32-bit build can't be recognized as a valid win32 application
 `ERROR: error compiling anonymous: could not load library "libhttp_parser32.dll"
%1 is not a valid Win32 application.`
The error comes on  64-bit julia (perhaps this is expected) and 64 bit windows.

In any case the 64 bit dll gives the following:

I built the latest version of http-parser and tried
`ver = ccall((:http_parser_url_init,"libhttp_parser64.dll"), Culong, ())`
with error
```
ERROR: ccall: could not find function http_parser_url_init in library libhttp_parser64.dll
 in anonymous at .\<missing>:?
```

**Comment by ranjanan** [comment]
This is 0.1.2 wasn't tagged in METADATA (https://github.com/JuliaLang/METADATA.jl/pull/5278). This is still broken on Windows

**Comment by musm** [comment]
Are you sure since I cross-compiled http-parser v2.40 ?

**Comment by ranjanan** [comment]
Yeah, this is still broken on Windows. I cross-compiled v2.7.1 and then replaced the dll with my own, and now it's fixed. I can upload my binary to S3 if this is fine. (I have built only for 64 bit though)

**Comment by musm** [comment]
What's in your Makefile?

**Comment by ranjanan** [comment]
@musm It now works on windows (#60). Can you delete your binaries and try again?

**Comment by musm** [comment]
I just did, seems like the binaries haven't been properly uploaded?
