### ISSUE TITLE
Not using system library

### ISSUE THREAD

**Issue by nico202** [JuliaWeb/HttpParser.jl#74]
Hi, I have libhttp_parser.so in the LD_LIBRARY_PATH. Other packages (like MbedTLS) try to use the system library if exists, and then fall back to the compilation. This package alwasy tries to compile. Since I'm on NixOS, the file /sbin/ldconfig does not exists, and so the build fails and the package can't be installed

**Comment by nico202** [comment]
I can confirm that bypassing the install and adding manually the file deps.jl with content:

    const lib = "libhttp_parser"

the pakage works as expected

**Comment by yuyichao** [comment]
It works fine for me, what local version do you have?

**Comment by nico202** [comment]
version=v"2.7.1"
