### ISSUE TITLE
HttpParser Build Errors [LoadError: HttpParser not properly installed]

### ISSUE THREAD

**Issue by anirudhmurali** [JuliaWeb/HttpParser.jl#81]
I used Julia 0.6.2 as Kernel for my Jupyter notebook, and wanted to use Requests.jl for HTTP Requests (https://github.com/JuliaWeb/Requests.jl). **Release: x86_64-pc-linux-gnu.**

Tried in my local Mac with **Release: x86_64-apple-darwin14.5.0**, works.

Precompilation of HttpParser failed:

![image](https://user-images.githubusercontent.com/3096325/35563317-4bba421e-05dc-11e8-8746-225b329692ce.png)

and on building HttpParser, I'm getting this error:

![image](https://user-images.githubusercontent.com/3096325/35563379-802a0534-05dc-11e8-8b8e-0fb4e4b3c986.png)

**Comment by tomaklutfu** [comment]
Probably, you are missing `unzip` command.

**Comment by anirudhmurali** [comment]
Help.

**Comment by anirudhmurali** [comment]
@aviks

**Comment by anirudhmurali** [comment]
Installing `build-essential` with `apt-get install build-essential` helped. The julia:0.6 misses unzip, make, gcc.

**Comment by anirudhmurali** [comment]
Also: `apt-get install unzip`
