### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by Nosferican** [JuliaWeb/HttpParser.jl#95]
Is this active or has it been de facto deprecated in favor of [Gumbo.jl](https://github.com/JuliaWeb/Gumbo.jl)?

**Comment by quinnj** [comment]
This should definitely be deprecated; HTTP ships w/ a whole parsing submodule that should be used instead.

**Comment by aviks** [comment]
closed by https://github.com/JuliaWeb/HttpParser.jl/commit/d4a11123aa8c3f6d355dc0bdde6cde266f4f492b
